import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRef } from 'react'
import { TextForm, TodoTable } from '../components'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  const inputRef = useRef<HTMLInputElement>(null)

  return (
    <div className={styles.container}>
      <Head>
        <title>Vtech todo list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>
        Welcome to <a href="#">Todo List!</a>
      </h1>

      <main className={styles.main}>
        <TextForm
          inputRef={inputRef}
        />
        <TodoTable
          inputRef={inputRef}
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
